---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Developer:
    - Algorithm Github:
        - abbr: GH
          href: https://github.com/Algorithm-Productions

- Project Management:
    - Coda:
        - abbr: CO
          href: https://coda.io/workspaces/ws-8pEHfWgZv9/docs

