

- Services:

    - Uptime Kuma:
        description: Monitors service uptime and notifies slack
        icon: si-uptimekuma
        href: http://algo-web:3001
        ping: http://uptime-kuma:3001
        server: my-docker
        container: uptime-kuma
        widget:
            type: uptimekuma
            url: http://uptime-kuma:3001
            slug: statuspageslug

    - Speedtest:
        description: Runs speedtest on algo-web server
        icon: si-speedtest
        href: http://algo-web:8765
        ping: http://speedtest:80
        server: my-docker
        container: speedtest
        widget:
            type: speedtest
            url: http://speedtest:80

- Network Monitoring:

#    - Caddy:
#        description: Caddy
#        icon: caddy.png
#        ping: http://caddy:9090
#        server: my-docker
#        container: caddy

    - Grafana:
        description: Dashboards of studio render machines
        icon: si-grafana
        href: http://algo-web:3000
        ping: http://grafana:3000
        server: my-docker
        container: grafana
        widget:
            type: grafana
            url: http://grafana:3000
            username: admin
            password: AlgoPass5

    - Prometheus:
        description: Metrics logging database
        icon: si-prometheus
        href: http://algo-web:9090
        ping: http://prometheus:9090
        server: my-docker
        container: prometheus
        widget:
            type: prometheus
            url: http://prometheus:9090

    - cAdvisor:
        description: Container monitoring tool
        icon: cadvisor.png
        href: http://algo-web:8085
        ping: http://cadvisor:8080
        server: my-docker
        container: cadvisor
