- logo:
    icon: home-assistant.png

- search:
    provider: google # google, duckduckgo, bing, baidu, brave or custom
    focus: true # Optional, will set focus to the search bar on page load
    target: _blank # One of _self, _blank, _parent or _top

- resources:
    label: System
    cpu: true
    memory: true

#- resources:
#    label: Storage
#    disk: /mnt/storage

- openmeteo:
    label: Dublin #optional
    latitude: 53.34
    longitude: -6.22
    timezone: Europe/Dublin # optional
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
